---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-applier
  namespace: monitoring
subjects:
  - kind: ServiceAccount
    name: argocd-server
    namespace: argocd
roleRef:
  kind: Role
  name: argocd-applier
  apiGroup: rbac.authorization.k8s.io
